name: CI/CD Pipeline

on:
  push:
    branches:
      - pipeline

jobs:
  build-push-to-ecr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Login to ECR
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region eu-central-1
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 383523838589.dkr.ecr.eu-central-1.amazonaws.com/eschool

    - name: Build and Push Docker image to ECR
      run: |
        docker build -t frontend:latest .
        docker tag frontend:latest 383523838589.dkr.ecr.eu-central-1.amazonaws.com/eschool
        docker push 383523838589.dkr.ecr.eu-central-1.amazonaws.com/eschool
    
