name: CI/CD Pipeline

on:
  push:
    branches:
      - pipeline

jobs:
  build-push-to-ecr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Login to ECR
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region eu-central-1
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 383523838589.dkr.ecr.eu-central-1.amazonaws.com/eschool-frontend

    - name: Build and Push Docker image to ECR
      run: |
        export DATE=$(date +%F_%H-%M-%S)
        docker build -t frontend:latest .
        docker tag frontend:latest 383523838589.dkr.ecr.eu-central-1.amazonaws.com/eschool-frontend:latest
        docker tag frontend:latest 383523838589.dkr.ecr.eu-central-1.amazonaws.com/eschool-frontend:frontend_$DATE
        docker push 383523838589.dkr.ecr.eu-central-1.amazonaws.com/eschool-frontend:latest
        docker push 383523838589.dkr.ecr.eu-central-1.amazonaws.com/eschool-frontend:frontend_$DATE
        
  deploy-to-ec2:
    needs: build-push-to-ecr
    runs-on: ubuntu-latest

    steps:
    - name: Decode SSH Key
      run: |
        echo "${{ secrets.SSH_KEY }}" > ./bastion
        chmod 400 bastion

    - name: Deploy to EC2 via Bastion
      run: |
        ssh -o StrictHostKeyChecking=no -i ./bastion ec2-user@${{ secrets.BASTION_HOST }} "ssh -o StrictHostKeyChecking=no -i ~/.ssh/bastion ec2-user@${{ secrets.FRONTEND_HOST }} 'aws ecr get-login-password --region eu-central-1 | sudo docker login --username AWS --password-stdin 383523838589.dkr.ecr.eu-central-1.amazonaws.com/eschool-frontend'"
        ssh -o StrictHostKeyChecking=no -i ./bastion ec2-user@${{ secrets.BASTION_HOST }} "ssh -o StrictHostKeyChecking=no -i ~/.ssh/bastion ec2-user@${{ secrets.FRONTEND_HOST }} 'sudo docker kill $(sudo docker ps -q) 2> /dev/null && sudo docker rm $(sudo docker ps -a -q) 2> /dev/null'"
        ssh -o StrictHostKeyChecking=no -i ./bastion ec2-user@${{ secrets.BASTION_HOST }} "ssh -o StrictHostKeyChecking=no -i ~/.ssh/bastion ec2-user@${{ secrets.FRONTEND_HOST }} 'sudo docker pull 383523838589.dkr.ecr.eu-central-1.amazonaws.com/eschool-frontend:latest && sudo docker run -d -p 80:80 383523838589.dkr.ecr.eu-central-1.amazonaws.com/eschool-frontend:latest'"
