name: CI/CD Pipeline

on:
  push:
    branches:
      - pipeline

jobs:
  build-push-to-ecr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Login to ECR
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region eu-central-1 # replace with your region
        $(aws ecr get-login --no-include-email --region eu-central-1) # replace with your region

    - name: Build and Push Docker image to ECR
      run: |
        docker build -t public.ecr.aws/p2c4r2s8/eschool/eschool:latest . # replace with your ECR URL and repo name
        docker push public.ecr.aws/p2c4r2s8/eschool/eschool:latest
